# Generated by Django 2.2.2 on 2019-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes_series', '0002_filme_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='cover',
            field=models.FileField(blank=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genre',
            field=models.CharField(choices=[('ACAO', 'Ação'), ('COMEDIA', 'Comédia'), ('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('DOCUMENTARIO', 'Documentário'), ('FANTASIA', 'Fantasia'), ('AVENTURA', 'Aventura')], default='ACAO', max_length=50),
        ),
    ]
